%import common.CNAME
%import common.SIGNED_INT
%import common.WS
%ignore WS
%ignore COMMENT

name        : CNAME
number      : SIGNED_INT
program     : assignment*
assignment  : name ":=" expression
?expression : literal
            | expression operator expression
            | "(" expression ")"
?literal    : number
            | name
?operator   : "*" -> mul
            | "+" -> add

COMMENT : /;[^\n]*/
